### ISSUE TITLE
Lazy-Load not loading properly

### ISSUE THREAD

**Issue by AsenCME** [hilongjw/vue-lazyload#183]
Form what I can see the problem is that it loads the image but doesn't change the loading SVG to the actual URL of the image. It also properly loads and changes the background URL of 3 of the 20 images I have on my website.

**Comment by rriixx** [comment]
i have the same issue. It randomly doesn't replace the src attribute with the image url. Sometimes images are loaded sometimes not.
Any advise?

I use lazy loading in my carousel (vue-carousel)

**Comment by AsenCME** [comment]
I fixed it while ago actually. At the time of making the project I was using Firebase in conjunction with Vue.JS 2. I was never able to fully understand the issue but changing all of the pictures on the Firebase storage bucket from '*.jpg' to '*.png' resolved it.

**Comment by bmpf** [comment]
I'm still experiencing this issue, and it appears to be isolated to Chrome-based system browsers. Additionally, it seems that this particular problem is specific to the 'v-lazy:background-image' directive.
